name: Rector Run

on:
    pull_request: null
    push:
        branches:
            - main

jobs:
    rector_run:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                php_version: ['8.1', '8.2']

        steps:
            -   uses: actions/checkout@v2

            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php_version }}
                    coverage: none

            -   run: php bin/rector --version --ansi

            -   run: php bin/rector list --ansi
