name: Laravel Pint
on: pull_request
jobs:
  pint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: "laravel-pint"
          uses: aglipanci/laravel-pint-action@2.3.0
          with:
            preset: laravel
            verboseMode: true
